import abc
from ..agents.i_agent import IAgent
from ..util.function import Function

class IExecCycle(metaclass=abc.ABCMeta):
    @abc.abstractclassmethod
    def exec(self, agents: list[IAgent], functions: list[Function]) -> list[int]:
        """
        Returns:
            time (int): the number of times for running (cycle)
            sum_messages (int): the number of messages generated by whole agents
        """
        raise NotImplementedError()